import { UiTranslations } from "./types";

export const LOCALIZED_DICTS: Record<string, UiTranslations> = {
  English: {
    mindAnalyzer: "Mind Analyzer",
    distortionLibrary: "Distortion Library",
    newReflection: "New Reflection",
    searchReflections: "Search Reflections",
    allEmotions: "All Emotions",
    allDistortions: "All Distortions",
    pastReflections: "Past Reflections",
    statusProtected: "ACTIVE MIND LAB WORKSPACE",
    howItWorksTitle: "Deconstruct Your Thoughts",
    howItWorksDesc: "Our advanced CBT cognitive modeling engine analyzes your raw thoughts, highlights cognitive biases, and constructs personalized psychological exercises.",
    freeJournalTab: "Freeform Journal",
    cbtAnalyzerTab: "CBT Analyzer",
    voiceJournalTab: "Voice Journal Simulation",
    loadSampleButton: "Load Sample",
    writeFreelyPlaceholder: "Write whatever is on your mind... Let your feelings flow freely, write as much as you need.",
    situationLabel: "What is the situation?",
    situationPlaceholder: "E.g., My boss didn't reply to my morning message...",
    thoughtsLabel: "What are your automatic thoughts?",
    thoughtsPlaceholder: "E.g., He is planning to fire me. I'm doing a terrible job...",
    feelingsLabel: "What are your feelings?",
    feelingsPlaceholder: "E.g., Anxious (80%), Sad (50%), Nervous (90%)...",
    deconstructButton: "Deconstruct Mind Patterns",
    deconstructingMind: "Deconstructing Mind Patterns...",
    loadingSubtitle: "Gemini is checking your thoughts for cognitive biases, calculating emotional spectrum intensity, and building specialized CBT exercises...",
    detectedLanguageBadge: "Detected Language: English",
    severeDistress: "Severe Overwhelm",
    moderateDistress: "Moderate Distress",
    mildDistress: "Mild Discomfort",
    companionVoiceLabel: "Companion Voice",
    synthesisTitle: "Therapeutic Synthesis",
    spectrumTitle: "Intensity & Spectrum",
    arousalStateTitle: "Arousal & Emotion State",
    intensityLabel: "Intensity",
    primaryEmotionLabel: "Primary State",
    restructuringTitle: "Thought Restructuring",
    reframeTableTitle: "Cognitive Reframing Table",
    automaticTrapLabel: "Automatic Distortion (The Trap)",
    rationalReframeLabel: "Rational Alternative (Self-Compassion Reframe)",
    cbtProbingPromptLabel: "CBT Self-Inquiry Question",
    biasScannerTitle: "Thinking Error Audit",
    distortionScannerTitle: "Detected Cognitive Distortions",
    activeExerciseLabel: "Active Self-Discovery Exercise",
    exerciseWorkspaceLabel: "REFLECTIVE EXERCISE WORKSPACE",
    exerciseWorkspacePlaceholder: "Document your observations, answers, or feelings while going through this exercise. Saving will append this to your history log permanently.",
    saveReflectionButton: "Log Reflections",
    healthyFlowDetected: "Healthy Cognitive Flow Detected",
    healthyFlowDesc: "Fantastic! Gemini didn't detect any severe thinking distortions or mental loops in your reflection. Your logic is highly balanced, rational, and adaptive.",
    identifiedInThoughts: "Identified in your thoughts:",
    therapeuticBreakdown: "Therapeutic Breakdown:",
    hideUndetected: "Hide undetected mental distortions",
    showUndetected: "Show undetected mental distortions",
    workThroughSteps: "WORK THROUGH THE EXERCISE STEPS:",
    allStepsDone: "All Steps Done!",
    savingReflection: "Saving reflection...",
    reflectionAppended: "Reflection Appended!"
  },
  Persian: {
    mindAnalyzer: "آنالیزور ذهن",
    distortionLibrary: "کتابخانه تحریف‌ها",
    newReflection: "ثبت بازتاب جدید",
    searchReflections: "جستجوی بازتاب‌ها",
    allEmotions: "همه احساسات",
    allDistortions: "همه تحریف‌ها",
    pastReflections: "بازتاب‌های گذشته",
    statusProtected: "فضای فعال ذهن‌پژوهی",
    howItWorksTitle: "مهندسی و تحلیل افکار خودکار",
    howItWorksDesc: "موتور مدل‌سازی شناختی CBT ما افکار خام شما را تحلیل کرده، خطاهای ذهنی را برجسته نموده و تمرینات روان‌شناختی شخصی‌سازی‌شده می‌سازد.",
    freeJournalTab: "دفترچه یادداشت آزاد",
    cbtAnalyzerTab: "آنالیزور شناختی رفتاری (CBT)",
    voiceJournalTab: "شبیه‌ساز ژورنال صوتی",
    loadSampleButton: "بارگذاری نمونه",
    writeFreelyPlaceholder: "هر آنچه در ذهن دارید بنویسید... اجازه دهید احساساتتان جاری شوند.",
    situationLabel: "موقعیت چیست؟ (چه اتفاقی افتاده است؟)",
    situationPlaceholder: "مثال: مدیرم به پیام صبحگاهی من پاسخ نداد...",
    thoughtsLabel: "افکار خودکار شما چیست؟ (به خودتان چه می‌گویید؟)",
    thoughtsPlaceholder: "مثال: او می‌خواهد مرا اخراج کند. من کارم را افتضاح انجام می‌دهم...",
    feelingsLabel: "احساسات و شدت آن‌ها چقدر است؟",
    feelingsPlaceholder: "مثال: اضطراب (۸۰٪)، غم (۵۰٪)، نگرانی (۹۰٪)...",
    deconstructButton: "شکافتن و تحلیل الگوهای ذهنی",
    deconstructingMind: "در حال تحلیل الگوهای ذهنی...",
    loadingSubtitle: "هوش مصنوعی در حال بررسی سوگیری‌های شناختی، محاسبه طیف‌های احساسی و طراحی تمرینات اختصاصی است...",
    detectedLanguageBadge: "زبان شناسایی شده: فارسی",
    severeDistress: "سرریز احساسی شدید",
    moderateDistress: "پریشانی متوسط",
    mildDistress: "ناآرامی خفیف",
    companionVoiceLabel: "صدای همدل",
    synthesisTitle: "سنتز درمانی و روان‌شناختی",
    spectrumTitle: "شدت و طیف احساسی",
    arousalStateTitle: "برانگیختگی و حالت عاطفی",
    intensityLabel: "شدت",
    primaryEmotionLabel: "حالت اصلی",
    restructuringTitle: "بازسازی فکری",
    reframeTableTitle: "جدول قاب‌بندی مجدد شناختی",
    automaticTrapLabel: "تحریف خودکار (تله ذهنی)",
    rationalReframeLabel: "جایگزین منطقی (قاب‌بندی شفقت به خود)",
    cbtProbingPromptLabel: "پرسش خودکاوی CBT",
    biasScannerTitle: "ممیزی خطاهای فکری",
    distortionScannerTitle: "تحریف‌های شناختی شناسایی‌شده",
    activeExerciseLabel: "تمرین فعال خودشناسی",
    exerciseWorkspaceLabel: "کاربرگ تمرین خوداندیشی",
    exerciseWorkspacePlaceholder: "مشاهدات، پاسخ‌ها یا احساسات خود را در حین انجام این تمرین یادداشت کنید. ذخیره کردن، این را به تاریخچه شما اضافه می‌کند.",
    saveReflectionButton: "ثبت بازتاب‌ها",
    healthyFlowDetected: "جریان شناختی سالم شناسایی شد",
    healthyFlowDesc: "عالی است! هوش مصنوعی هیچ تحریف شناختی شدید یا چرخه فکری مخربی در افکار شما پیدا نکرد. تفکر شما بسیار متعادل، منطقی و منعطف است.",
    identifiedInThoughts: "شناسایی شده در افکار شما:",
    therapeuticBreakdown: "تحلیل روان‌شناختی:",
    hideUndetected: "پنهان کردن تحریف‌های شناختی بررسی‌شده",
    showUndetected: "نمایش تحریف‌های شناختی بررسی‌شده",
    workThroughSteps: "مراحل انجام تمرین:",
    allStepsDone: "تمام مراحل انجام شد!",
    savingReflection: "در حال ذخیره‌سازی...",
    reflectionAppended: "بازتاب با موفقیت ثبت شد!"
  },
  Spanish: {
    mindAnalyzer: "Analizador de Mente",
    distortionLibrary: "Biblioteca de Sesgos",
    newReflection: "Nueva Reflexión",
    searchReflections: "Buscar Reflexiones",
    allEmotions: "Todas las Emociones",
    allDistortions: "Todos los Sesgos",
    pastReflections: "Reflexiones Pasadas",
    statusProtected: "ESPACIO ACTIVO DE ANÁLISIS MENTAL",
    howItWorksTitle: "Deconstruye tus Pensamientos",
    howItWorksDesc: "Nuestro avanzado motor de modelado cognitivo TCC analiza tus pensamientos, resalta los sesgos cognitivos y construye ejercicios psicológicos personalizados.",
    freeJournalTab: "Diario Libre",
    cbtAnalyzerTab: "Analizador TCC",
    voiceJournalTab: "Simulación de Voz",
    loadSampleButton: "Cargar Ejemplo",
    writeFreelyPlaceholder: "Escribe lo que tengas en mente... Deja fluir tus emociones y escribe tanto como necesites.",
    situationLabel: "¿Cuál es la situación?",
    situationPlaceholder: "Ej. Mi jefe no respondió a mi mensaje de la mañana...",
    thoughtsLabel: "¿Cuáles son tus pensamientos automáticos?",
    thoughtsPlaceholder: "Ej. Me va a despedir. Estoy haciendo un trabajo terrible...",
    feelingsLabel: "¿Cuáles son tus emociones/sentimientos?",
    feelingsPlaceholder: "Ej. Ansioso (80%), Triste (50%), Nervioso (90%)...",
    deconstructButton: "Deconstruir Patrones Mentales",
    deconstructingMind: "Deconstructing Mind Patterns...",
    loadingSubtitle: "Gemini está analizando tus pensamientos, calculando el espectro emocional y diseñando ejercicios de TCC especializados...",
    detectedLanguageBadge: "Idioma Detectado: Español",
    severeDistress: "Agobio Severo",
    moderateDistress: "Angustia Moderada",
    mildDistress: "Malestar Leve",
    companionVoiceLabel: "Voz del Acompañante",
    synthesisTitle: "Síntesis Terapéutica",
    spectrumTitle: "Intensidad y Espectro",
    arousalStateTitle: "Estado de Emoción y Activación",
    intensityLabel: "Intensidad",
    primaryEmotionLabel: "Estado Primario",
    restructuringTitle: "Reestructuración Cognitiva",
    reframeTableTitle: "Tabla de Reestructuración Cognitiva",
    automaticTrapLabel: "Distorsión Automática (La Trampa)",
    rationalReframeLabel: "Alternativa Racional (Reencuadre de Autocompasión)",
    cbtProbingPromptLabel: "Pregunta de Autoindagación TCC",
    biasScannerTitle: "Auditoría de Errores de Pensamiento",
    distortionScannerTitle: "Distorsiones Cognitivas Detectadas",
    activeExerciseLabel: "Ejercicio de Autodescubrimiento Activo",
    exerciseWorkspaceLabel: "ESPACIO DE TRABAJO DE REFLEXIÓN",
    exerciseWorkspacePlaceholder: "Documenta tus observaciones o sentimientos durante este ejercicio. Al guardar se añadirá permanentemente a tu historial.",
    saveReflectionButton: "Registrar Reflexiones"
  },
  French: {
    mindAnalyzer: "Analyseur de Pensées",
    distortionLibrary: "Bibliothèque des Biais",
    newReflection: "Nouvelle Réflexion",
    searchReflections: "Rechercher",
    allEmotions: "Toutes les Émotions",
    allDistortions: "Toutes les Distorsions",
    pastReflections: "Réflexions Passées",
    statusProtected: "ESPACE D'ANALYSE COGNITIVE ACTIF",
    howItWorksTitle: "Déconstruisez vos Pensées",
    howItWorksDesc: "Notre moteur de modélisation TCC avancé analyse vos pensées brutes, met en évidence les biais cognitifs et élabore des exercices psychologiques personnalisés.",
    freeJournalTab: "Journal Libre",
    cbtAnalyzerTab: "Analyseur TCC",
    voiceJournalTab: "Simulation Vocale",
    loadSampleButton: "Charger l'Exemple",
    writeFreelyPlaceholder: "Écrivez tout ce qui vous passe par la tête... Laissez libre cours à vos sentiments.",
    situationLabel: "Quelle est la situation ?",
    situationPlaceholder: "Ex. Mon patron n'a pas répondu à mon message ce matin...",
    thoughtsLabel: "Quelles sont vos pensées automatiques ?",
    thoughtsPlaceholder: "Ex. Il va me licencier. Je fais un travail horrible...",
    feelingsLabel: "Quels sont vos sentiments ?",
    feelingsPlaceholder: "Ex. Anxieux (80%), Triste (50%), Nervieux (90%)...",
    deconstructButton: "Déconstruire les Schémas Mentaux",
    deconstructingMind: "Deconstructing Mind Patterns...",
    loadingSubtitle: "Gemini analyse vos pensées, évalue l'intensité de vos émotions et crée des exercices de TCC sur mesure...",
    detectedLanguageBadge: "Langue Détectée: Français",
    severeDistress: "Détresse Sévère",
    moderateDistress: "Anxiété Modérée",
    mildDistress: "Inconfort Léger",
    companionVoiceLabel: "Voix d'Accompagnement",
    synthesisTitle: "Synthèse Thérapeutique",
    spectrumTitle: "Intensité & Spectre",
    arousalStateTitle: "État Émotionnel & Éveil",
    intensityLabel: "Intensité",
    primaryEmotionLabel: "État Principal",
    restructuringTitle: "Restructuration Cognitive",
    reframeTableTitle: "Tableau de Recadrage Cognitif",
    automaticTrapLabel: "Distorsion Automatique (Le Piège)",
    rationalReframeLabel: "Alternative Rationnelle (Recadrage de Bienveillance)",
    cbtProbingPromptLabel: "Question d'Auto-Observation TCC",
    biasScannerTitle: "Audit des Erreurs de Pensée",
    distortionScannerTitle: "Distorsions Cognitives Détectées",
    activeExerciseLabel: "Exercice Actif d'Auto-Découverte",
    exerciseWorkspaceLabel: "ESPACE DE RÉFLEXION PRATIQUE",
    exerciseWorkspacePlaceholder: "Notez vos observations, vos réponses ou vos sentiments durant cet exercice. L'enregistrement l'ajoutera de manière permanente à votre historique.",
    saveReflectionButton: "Enregistrer la Réflexion"
  },
  German: {
    mindAnalyzer: "Gedanken-Analysator",
    distortionLibrary: "Verzerrungsbibliothek",
    newReflection: "Neue Reflexion",
    searchReflections: "Reflexionen suchen",
    allEmotions: "Alle Emotionen",
    allDistortions: "Alle Verzerrungen",
    pastReflections: "Vergangene Reflexionen",
    statusProtected: "AKTIVER KOGNITIVER ARBEITSBEREICH",
    howItWorksTitle: "Dekonstruieren Sie Ihre Gedanken",
    howItWorksDesc: "Unsere fortschrittliche kognitive KVT-Modellierungs-Engine analysiert Ihre Gedanken, hebt kognitive Verzerrungen hervor und erstellt personalisierte psychologische Übungen.",
    freeJournalTab: "Freies Tagebuch",
    cbtAnalyzerTab: "KVT-Analysator",
    voiceJournalTab: "Sprachtagebuch-Simulation",
    loadSampleButton: "Beispiel laden",
    writeFreelyPlaceholder: "Schreiben Sie auf, was Ihnen durch den Kopf geht... Lassen Sie Ihren Gefühlen freien Lauf.",
    situationLabel: "Was ist die Situation?",
    situationPlaceholder: "Z.B. Mein Chef hat nicht auf meine morgendliche Nachricht geantwortet...",
    thoughtsLabel: "Was sind Ihre automatischen Gedanken?",
    thoughtsPlaceholder: "Z.B. Er wird mich feuern. Ich mache schreckliche Arbeit...",
    feelingsLabel: "Was sind Ihre Gefühle?",
    feelingsPlaceholder: "Z.B. Ängstlich (80%), Traurig (50%), Nervös (90%)...",
    deconstructButton: "Denkmuster dekonstruieren",
    deconstructingMind: "Deconstructing Mind Patterns...",
    loadingSubtitle: "Gemini sucht nach kognitiven Verzerrungen, berechnet emotionale Spektren und erstellt maßgeschneiderte KVT-Übungen...",
    detectedLanguageBadge: "Erkannte Sprache: Deutsch",
    severeDistress: "Schwere Überforderung",
    moderateDistress: "Mittlere Belastung",
    mildDistress: "Leichtes Unbehagen",
    companionVoiceLabel: "Begleiter-Stimme",
    synthesisTitle: "Therapeutische Synthese",
    spectrumTitle: "Intensität & Spektrum",
    arousalStateTitle: "Aktivierungs- & Emotionen-Zustand",
    intensityLabel: "Intensität",
    primaryEmotionLabel: "Hauptzustand",
    restructuringTitle: "Gedankenumstrukturierung",
    reframeTableTitle: "Kognitive Reframing-Tabelle",
    automaticTrapLabel: "Automatische Verzerrung (Die Falle)",
    rationalReframeLabel: "Rationale Alternative (Selbstmitgefühl-Reframing)",
    cbtProbingPromptLabel: "KVT-Selbstbefragung",
    biasScannerTitle: "Denkfehler-Audit",
    distortionScannerTitle: "Erkannte kognitive Verzerrungen",
    activeExerciseLabel: "Aktive Selbstentdeckungs-Übung",
    exerciseWorkspaceLabel: "REFLEXIONS-ÜBUNGSBEREICH",
    exerciseWorkspacePlaceholder: "Dokumentieren Sie Ihre Beobachtungen, Antworten oder Gefühle während dieser Übung. Das Speichern fügt dies dauerhaft Ihrem Verlauf hinzu.",
    saveReflectionButton: "Reflexionen speichern"
  }
};

export const SUPPORTED_LANGUAGES = Object.keys(LOCALIZED_DICTS);
